-- MySQL Script generated by MySQL Workbench
-- Mon Sep 17 22:44:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restauranteDoBigode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restauranteDoBigode
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restauranteDoBigode` DEFAULT CHARACTER SET utf8 ;
USE `restauranteDoBigode` ;

-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Funcionarios` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(10) NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idFuncionario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Pessoas` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  `cpf` DECIMAL(14) NULL,
  `telefone` DECIMAL(12) NULL,
  `idPessoaCliente` INT NULL,
  `idPessoaFuncionario` INT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC),
  INDEX `idPessoaCliente_idx` (`idPessoaCliente` ASC),
  INDEX `idPessoaFuncionario_idx` (`idPessoaFuncionario` ASC),
  CONSTRAINT `idPessoaCliente`
    FOREIGN KEY (`idPessoaCliente`)
    REFERENCES `restauranteDoBigode`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPessoaFuncionario`
    FOREIGN KEY (`idPessoaFuncionario`)
    REFERENCES `restauranteDoBigode`.`Funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Produtos` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NULL,
  `valor_produto` DOUBLE(4,2) NULL,
  `peso` DECIMAL(4,2) NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `valor_total` DOUBLE(4,2) NULL,
  `quantidade` DECIMAL(2) NULL,
  `idPedidoCliente` INT NULL,
  `idPedidoProduto` INT NULL,
  PRIMARY KEY (`idPedidos`),
  UNIQUE INDEX `idPedidos_UNIQUE` (`idPedidos` ASC),
  INDEX `idPedidoCliente_idx` (`idPedidoCliente` ASC),
  INDEX `idPedidoProduto_idx` (`idPedidoProduto` ASC),
  CONSTRAINT `idPedidoCliente`
    FOREIGN KEY (`idPedidoCliente`)
    REFERENCES `restauranteDoBigode`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idPedidoProduto`
    FOREIGN KEY (`idPedidoProduto`)
    REFERENCES `restauranteDoBigode`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Vendas` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `valor_unidade` DOUBLE(4,2) NULL,
  `valor_total` DOUBLE(4,2) NULL,
  `idVendaFuncionario` INT NULL,
  `idVendaPedido` INT NULL,
  INDEX `idVendaFuncionario_idx` (`idVendaFuncionario` ASC),
  INDEX `idVendaPedido_idx` (`idVendaPedido` ASC),
  PRIMARY KEY (`idVenda`),
  UNIQUE INDEX `idVenda_UNIQUE` (`idVenda` ASC),
  CONSTRAINT `idVendaFuncionario`
    FOREIGN KEY (`idVendaFuncionario`)
    REFERENCES `restauranteDoBigode`.`Funcionarios` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVendaPedido`
    FOREIGN KEY (`idVendaPedido`)
    REFERENCES `restauranteDoBigode`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Enderecos` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua/quadra` VARCHAR(150) NULL,
  `conjunto` VARCHAR(3) NULL,
  `numero` DECIMAL(3) NULL,
  `idEnderecoPessoa` INT NULL,
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC),
  INDEX `idEnderecoPessoa_idx` (`idEnderecoPessoa` ASC),
  CONSTRAINT `idEnderecoPessoa`
    FOREIGN KEY (`idEnderecoPessoa`)
    REFERENCES `restauranteDoBigode`.`Pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Pagamentos` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `tipo_pagamento` VARCHAR(45) NULL,
  `valor_pago` DOUBLE(4,2) NULL,
  `idPagamentoVenda` INT NULL,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC),
  INDEX `idPagamentoVenda_idx` (`idPagamentoVenda` ASC),
  CONSTRAINT `idPagamentoVenda`
    FOREIGN KEY (`idPagamentoVenda`)
    REFERENCES `restauranteDoBigode`.`Vendas` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restauranteDoBigode`.`Estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restauranteDoBigode`.`Estoques` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `quantidade` DECIMAL(3) NULL,
  `idEstoqueProduto` INT NULL,
  PRIMARY KEY (`idEstoque`),
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC),
  INDEX `idEstoqueProduto_idx` (`idEstoqueProduto` ASC),
  CONSTRAINT `idEstoqueProduto`
    FOREIGN KEY (`idEstoqueProduto`)
    REFERENCES `restauranteDoBigode`.`Produtos` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
